name: Java CI with Gradle
on:
  push:
    branches:
      - master
  pull_request:    
    branches:
      - master
permissions:
  pull-requests: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        
      - name: Check if dependency update
        id: check-dependency
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            COMMIT_MSG=$(git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }})
          else
            COMMIT_MSG=$(git log -1 --pretty=%B)
          fi
          if [[ "$COMMIT_MSG" == dependency:* ]]; then
            echo "is-dependency=true" >> $GITHUB_OUTPUT
          else
            echo "is-dependency=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          
      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          path: ~/.gradle/caches
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: '${{ runner.os }}-gradle-'
          
      - name: Make gradlew executable
        run: chmod +x gradlew
        
      - name: Compile the plugin
        if: steps.check-dependency.outputs.is-dependency == 'true'
        run: ./gradlew clean compileJava
        
      - name: Build the plugin
        if: steps.check-dependency.outputs.is-dependency == 'false'
        run: ./gradlew clean shadowJar
        
      - name: Upload built JAR
        uses: actions/upload-artifact@v7
        if: steps.check-dependency.outputs.is-dependency == 'false'
        with:
          name: ParcelLockers Dev Build
          path: build/libs/ParcelLockers*.jar
